### ISSUE TITLE
Error when installing through ESPHome

### ISSUE THREAD

**Issue by Xnygra** [synegic/esphome-smartevse-sensorbox#1]
Hello arpiecodes. 

Trying to install this on my Senorbox 2 and get this error when installing through EspHome. Me being a non-coder, I can not make any sense of the Logs, Could you possible help me understand what the problem is. Thank you. See attached full Logg

> /config/esphome/sensorbox-2.yaml: In function 'void setup()':
/config/esphome/sensorbox-2.yaml:178:27: error: 'esphome::sensor::Sensor* esphome::smartevse_sensorbox::SmartEVSESensorbox::ct1_current_' is private within this context
       return { id(sensorbox)->ct1_current_, id(sensorbox)->ct2_current_, id(sensorbox)->ct3_current_};
                           ^~~~~~~~~~~~
In file included from src/esphome.h:39,
                 from src/main.cpp:3:
src/esphome/components/smartevse_sensorbox/smartevse_sensorbox.h:77:79: note: declared private here
           esphome::sensor::Sensor* ct1_current_ = new esphome::sensor::Sensor();

<

[logs_sensorbox-2_compile.txt](https://github.com/arpiecodes/esphome-smartevse-sensorbox/files/13693184/logs_sensorbox-2_compile.txt)

**Comment by arpiecodes** [comment]
Hello @Xnygra, I've merged the latest code from develop branch (working properly here for months) into main. This should also contain a fix for the private error on compile. Could you try it out?

**Comment by Xnygra** [comment]
Hi arpiecodes, Thank you for very swift reply :) 
Unfortunately I got another set of errors:

INFO ESPHome 2023.11.6
INFO Reading configuration /config/esphome/sensorbox-2.yaml...
Failed config

smartevse_sensorbox: [source /config/esphome/sensorbox-2.yaml:83]
  id: sensorbox
  uart_id: uart_pic
  use_ct_readings: False
  ct_rotation: CW
  ct_wires: 4WIRE
  
  'power_consumed_phase_2' is a required option for [p1_sensors].
  p1_sensors:  [source /config/esphome/sensorbox-2.yaml:90]
    dsmr_version: dsmr_version
    
    [current_phase_1] is an invalid option for [p1_sensors]. Did you mean [voltage_phase_1]?
    current_phase_1: current_phase_1
    
    [current_phase_2] is an invalid option for [p1_sensors]. Did you mean [voltage_phase_2]?
    current_phase_2: current_phase_2
    
    [current_phase_3] is an invalid option for [p1_sensors]. Did you mean [voltage_phase_3]?
    current_phase_3: current_phase_3
    voltage_phase_1: voltage_phase_1
    voltage_phase_2: voltage_phase_2
    voltage_phase_3: voltage_phase_2
required key not provided

required key not provided

**Comment by arpiecodes** [comment]
Ah, I forgot to update the example yaml in the README. It's now updated, as there were some changes in develop branch. You will probably need to update your YAML as well according to the new example in the main branch.

**Comment by arpiecodes** [comment]
I found another potential issue after the merge from develop to main which I just fixed with a commit. Should all be good to go now! Let me know how it works out for you.

**Comment by Xnygra** [comment]
Works like a charm.

Thank you very much 🥇 

INFO ESPHome 2023.11.6
INFO Reading configuration /config/esphome/sensorbox-2.yaml...
INFO Updating https://github.com/arpiecodes/esphome-modbus-server.git@master
INFO Updating https://github.com/arpiecodes/esphome-smartevse-sensorbox.git@main
INFO Detected timezone 'Europe/Stockholm'
INFO Starting log output from sensorbox.local using esphome API
INFO Successfully connected to sensorbox in 0.342s
INFO Successful handshake with sensorbox in 0.114s
[18:49:31][I][app:102]: ESPHome version 2023.11.6 compiled on Dec 16 2023, 18:44:33
[18:49:31][C][status_led:019]: Status LED:
[18:49:31][C][status_led:020]:   Pin: GPIO32
